# Rockchip vendor U-Boot for RK3506.
#
# This builds U-Boot from the rockchip-linux/u-boot next-dev branch and
# combines it with rkbin blobs to produce the bootable images:
#
#   - idbloader.img  (DDR init + SPL — written to raw sectors on SD or SPI NAND)
#   - u-boot.itb     (U-Boot proper + OP-TEE as FIT image)
#
# The Rockchip boot chain is:
#   BootROM → idbloader.img (DDR + SPL) → u-boot.itb → kernel + DTB + initrd
{
  lib,
  stdenv,
  fetchFromGitHub,
  bison,
  flex,
  bc,
  dtc,
  openssl,
  swig,
  python3,
  ubootTools,
  rkbin,
  buildPackages,
}:

stdenv.mkDerivation {
  pname = "u-boot-rk3506";
  version = "unstable-2025-03-21";

  src = fetchFromGitHub {
    owner = "rockchip-linux";
    repo = "u-boot";
    rev = "b14196eade471bbc000c368f8555f2a2a1ecc17d";
    hash = "sha256-+poK56Y+AxZuXoEggbLUezzIIoZMpFZ7FtVmN7/XaQI=";
  };

  depsBuildBuild = [ buildPackages.stdenv.cc ];

  nativeBuildInputs = [
    bison
    flex
    bc
    dtc
    openssl
    swig
    python3
    ubootTools
  ];

  # Tell the Rockchip build scripts where to find rkbin blobs
  RKBIN = "${rkbin}";

  postPatch = ''
    patchShebangs scripts/ tools/ make.sh arch/arm/mach-rockchip/
  '';

  configurePhase = ''
    runHook preConfigure
    make rk3506_defconfig CROSS_COMPILE=${stdenv.cc.targetPrefix}
    runHook postConfigure
  '';

  buildPhase = ''
    runHook preBuild

    # Vendor U-Boot doesn't compile clean with GCC 15:
    #   -Werror=maybe-uninitialized in pinctrl drivers
    #   -Werror=enum-int-mismatch in command.c
    # Suppress these at the CFLAGS level since CONFIG_WERROR=y is baked in.
    make \
      CROSS_COMPILE=${stdenv.cc.targetPrefix} \
      KCFLAGS="-Wno-error=maybe-uninitialized -Wno-error=enum-int-mismatch -Wno-error=incompatible-pointer-types -Wno-error=int-conversion" \
      -j$NIX_BUILD_CORES

    # Generate idbloader.img (SPL + DDR init blob)
    # The idbloader combines the DDR init blob with SPL into a single image
    # that the BootROM loads from sector 64 on SD card
    tools/mkimage -n rk3506 -T rksd \
      -d ${rkbin}/bin/rk3506_ddr_750MHz_v1.06.bin:spl/u-boot-spl.bin \
      idbloader.img || true

    # If the above fails (mkimage format may differ), try the simpler concat approach
    if [ ! -f idbloader.img ]; then
      echo "mkimage rksd failed, using manual concatenation"
      cat ${rkbin}/bin/rk3506_ddr_750MHz_v1.06.bin spl/u-boot-spl.bin > idbloader.img
    fi

    # Generate u-boot.itb (FIT image with U-Boot + TEE)
    # For now we just install u-boot.bin; the FIT packing can be refined
    # once we validate the basic build
    if [ -f u-boot.itb ]; then
      echo "u-boot.itb already generated by build"
    else
      echo "NOTE: u-boot.itb not generated — install u-boot.bin directly"
    fi

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/bin

    # Core boot images
    cp idbloader.img $out/bin/ 2>/dev/null || true
    cp u-boot.itb $out/bin/ 2>/dev/null || true
    cp u-boot.bin $out/bin/ 2>/dev/null || true
    cp u-boot.img $out/bin/ 2>/dev/null || true
    cp spl/u-boot-spl.bin $out/bin/ 2>/dev/null || true

    # Device trees (for reference / override)
    mkdir -p $out/dtb
    cp arch/arm/dts/rk3506*.dtb $out/dtb/ 2>/dev/null || true

    # mkimage tool for boot script generation
    mkdir -p $out/tools
    cp tools/mkimage $out/tools/ 2>/dev/null || true

    runHook postInstall
  '';

  meta = {
    description = "Rockchip vendor U-Boot for RK3506";
    homepage = "https://github.com/rockchip-linux/u-boot";
    license = lib.licenses.gpl2Only;
    platforms = [ "armv7l-linux" ];
  };
}
